### PR TITLE
Generated documentation with Swagger

### PR DESCRIPTION
**Pull request by Santi-7**

### CODE REVIEW

**Comment by fjlopez** [comment]
Please, add an example in README.md explaining how to get or generate the documentation of the API.

**Comment by fjlopez** [comment]
See for example https://github.com/ismaro3/Laboratory-3-Restful-Web-Services

**Comment by fjlopez** [comment]
Two quick fixes and you have the :gift:. First, be consistent. In [Server.java](https://github.com/ismaro3/Laboratory-3-Restful-Web-Services/blob/master/src/main/java/rest/addressbook/Server.java) the server uses 8080 but data uses 8282. And second, you should provide information in 404 errors. For example, if I navigate to ```http://localhost:8282/contacts/person/3``` you should provide something useful.  Google can provide [some useful ideas](https://google.github.io/styleguide/jsoncstyleguide.xml)

**Comment by Santi-7** [comment]
I have added documentation about Swagger.

**Comment by fjlopez** [comment]
The description does provide neither a step-by-step description of how to generate the documentation nor a working URI that provides access to the documentation after `gradle server`. The provided URI [http://localhost:8282/api/resources.json](http://localhost:8282/api/resources.json) returns 404.

**Comment by Santi-7** [comment]
I have solved it. I had to create a Servlet container. Now, http://localhost:8282/api/resources.json returns a json with Swagger documentation

**Comment by fjlopez** [comment]
Accepted, but please remove from the documentation the line:

    We open Swagger UI local with http://localhost:8282/api/resources.json

**Pull request merged**
