### PR TITLE
Documenting with JSONDoc(Added Gift)

### PR DESCRIPTION
**Pull request by albert17**

### CODE REVIEW

**Comment by fjlopez** [comment]
As we have discussed this evening, you should provide a runnable example of how to use JSONDoc for generating documentation (e.g. see the optional part of http://jsondoc.org/how-to-spring-boot.html). 

The status moves from "_under review_" to "_requested enhancement_".

**Comment by albert17** [comment]
I have added a runnable example to use JSONDoc for generating documentation. Moreover I have added some information about configuring JSONDoc with Spring and its annotations.

**Comment by fjlopez** [comment]
Ops. The application is not a Spring Boot app but a simple Grizzly server. Thus, a Spring Boot annotation doesn't work. You can transform the app in a Spring Boot app (that can be done in following http://www.insaneprogramming.be/blog/2015/09/04/spring-jaxrs/) and then probably the annotation will work.

**Comment by albert17** [comment]
Now the application is a Spring Boot app and JSONDoc is working.

**Comment by fjlopez** [comment]
I just reverted the pull request because `gradle check` fails. Please fix it!!!

**Pull request merged**
